// ============================================================
// JEET ERP — Quotation Module Validation Schemas
// Zod schemas for quotations, lines, and approval logs
// ============================================================

import { z } from 'zod';

// 1. Quotation Line Item Schema
export const quotationLineSchema = z.object({
  id: z.string().uuid().optional(),
  quotation_id: z.string().uuid().optional(),
  line_number: z.number().int().positive(),
  pricing_item_id: z.string().uuid().nullable().optional(),
  item_code: z.string().nullable().optional(),
  description: z.string().min(1, 'Description is required'),
  system: z.string().min(1, 'System is required'),
  category: z.string().min(1, 'Category is required'),
  unit: z.string().min(1, 'Unit is required'),
  quantity: z.number().positive('Quantity must be greater than zero'),
  unit_sell_price: z.number().nonnegative('Unit sell price cannot be negative'),
  discount_pct: z.number().min(0).max(100).default(0),
  unit_sell_price_after_discount: z.number().nonnegative().optional(),
  line_total: z.number().nonnegative().optional(),
  vat_applicable: z.boolean().default(true),
  is_optional: z.boolean().default(false),
  notes: z.string().nullable().optional(),
  sort_order: z.number().int().nonnegative().optional()
});

// 2. Quotation Header Validation Schema (Creation / Edit)
export const quotationSchema = z.object({
  id: z.string().uuid().optional(),
  quotation_number: z.string().optional(), // generated by DB
  revision: z.number().int().nonnegative().default(0),
  revision_label: z.string().default('Rev.0'),
  status: z.enum([
    'DRAFT', 'PENDING_COMMERCIAL', 'PENDING_GM', 'APPROVED', 'SENT_TO_CLIENT',
    'ACCEPTED', 'REJECTED', 'REVISED', 'SUPERSEDED'
  ]).default('DRAFT'),
  boq_id: z.string().uuid('Invalid BOQ Reference'),
  project_id: z.string().uuid('Invalid Project Reference'),
  project_ref: z.string().min(1, 'Project reference is required'),
  tender_ref: z.string().nullable().optional(),
  previous_quotation_id: z.string().uuid().nullable().optional(),
  
  // Client details snapshot
  client_id: z.string().uuid('Invalid Client Reference'),
  client_name: z.string().min(1, 'Client name is required'),
  client_address_line1: z.string().nullable().optional(),
  client_address_line2: z.string().nullable().optional(),
  client_city: z.string().nullable().optional(),
  client_country: z.string().default('UAE'),
  
  // Client contact details
  client_contact_person: z.string().nullable().optional(),
  client_contact_email: z.string().email('Invalid contact email').or(z.literal('')).nullable().optional(),
  client_contact_phone: z.string().nullable().optional(),
  client_po_number: z.string().nullable().optional(),
  
  // Dates
  quotation_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Invalid date format (YYYY-MM-DD)'),
  valid_until: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Invalid date format (YYYY-MM-DD)'),
  
  // Subject & Scope
  subject: z.string().min(1, 'Subject is required'),
  scope_summary: z.string().max(2000, 'Scope summary must be less than 2000 characters').nullable().optional(),
  currency: z.string().default('AED'),
  
  // Financial values
  subtotal_ex_vat: z.number().nonnegative().default(0),
  discount_amount: z.number().nonnegative().default(0),
  subtotal_after_discount: z.number().nonnegative().default(0),
  vat_rate: z.number().default(5.00),
  vat_amount: z.number().nonnegative().default(0),
  grand_total_with_vat: z.number().nonnegative().default(0),
  grand_total_in_words: z.string().nullable().optional(),
  
  // Commercial Terms
  payment_terms: z.string().nullable().optional(),
  delivery_period: z.string().nullable().optional(),
  warranty_terms: z.string().nullable().optional(),
  terms_and_conditions: z.string().nullable().optional(),
  exclusions: z.string().nullable().optional(),
  inclusions: z.string().nullable().optional(),
  notes_internal: z.string().nullable().optional(),
  notes_client: z.string().nullable().optional(),
  
  // Lines
  lines: z.array(quotationLineSchema).min(1, 'Quotation must have at least one line item')
});

// 3. Approval Action Schema
export const quotationApprovalSchema = z.object({
  quotation_id: z.string().uuid(),
  stage: z.enum(['COMMERCIAL', 'GM', 'ESTIMATOR']),
  action: z.enum(['SUBMITTED', 'APPROVED', 'REJECTED', 'RETURNED']),
  comment: z.string().max(1000, 'Comment must be less than 1000 characters').nullable().optional(),
  signature_ref: z.string().nullable().optional()
});

export type QuotationLineInput = z.infer<typeof quotationLineSchema>;
export type QuotationInput = z.infer<typeof quotationSchema>;
export type QuotationApprovalInput = z.infer<typeof quotationApprovalSchema>;
