-- ============================================================
-- JEET ERP — Phase 2: pre-award LEADS -> tenders + boqs + quotations
-- GENERATED by scripts/seed_portfolio.py. Idempotent (ON CONFLICT).
-- Apply AFTER 20260617000000_seed_portfolio.sql. One lead = tender->boq->quotation(+1 line).
-- ============================================================
BEGIN;
SELECT set_config('jeet.admin_id',
  COALESCE((SELECT id::text FROM auth.users WHERE id='da475069-0381-42da-b1b2-7af0cadd54d8'),
           (SELECT id::text FROM auth.users ORDER BY created_at LIMIT 1)), false);

-- lead clients (upsert; most already exist from Phase 1)
INSERT INTO public.clients (id, name, country) VALUES ('82037870-19bb-59a7-aa74-24bd9ea37f1e'::uuid, 'TSC Limited (Sustainable City)', 'UAE') ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name;

INSERT INTO public.tenders (id, created_by, title, project_name, client_name, location, deadline_date, budget, status, scope_of_work) VALUES (
  '9489ed19-fa27-5add-be86-36db3666d418'::uuid, current_setting('jeet.admin_id')::uuid, 'Plaza Mosque & Grandiose Parking CCTV', 'Plaza Mosque & Grandiose Parking CCTV', 'TSC Limited (Sustainable City)', 'UAE', COALESCE('2026-01-23', CURRENT_DATE + 14), 105333.27, 'Submitted', 'Plaza Mosque & Grandiose Parking CCTV')
  ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, budget=EXCLUDED.budget, status=EXCLUDED.status;
INSERT INTO public.boqs (id, tender_id, created_by, status, version, items, cost_elements, financials) VALUES (
  'd3f8d0a1-7bfd-5f4c-a377-600cfa7da618'::uuid, '9489ed19-fa27-5add-be86-36db3666d418'::uuid, current_setting('jeet.admin_id')::uuid, 'draft', 1, '[]'::jsonb, '{}'::jsonb, jsonb_build_object('total_selling_price', 105333.27, 'unit_selling_price', 105333.27))
  ON CONFLICT (id) DO UPDATE SET financials=EXCLUDED.financials;
INSERT INTO public.quotations (id, quotation_number, revision, status, boq_id, project_id, project_ref, client_id, client_name, quotation_date, valid_until, subject, subtotal_ex_vat, subtotal_after_discount, vat_amount, grand_total_with_vat, currency, prepared_by) VALUES (
  'aa984fc3-f5c6-5d3d-b972-14999502762f'::uuid, '001-JEET- INTECH-DSC-004-2026', 2, 'SENT_TO_CLIENT', 'd3f8d0a1-7bfd-5f4c-a377-600cfa7da618'::uuid, '9489ed19-fa27-5add-be86-36db3666d418'::uuid, 'DSC-004-2026', '82037870-19bb-59a7-aa74-24bd9ea37f1e'::uuid, 'TSC Limited (Sustainable City)', COALESCE('2026-01-14', CURRENT_DATE), COALESCE('2026-01-23', CURRENT_DATE + 14), 'Plaza Mosque & Grandiose Parking CCTV', 105333.27, 105333.27, round(105333.27*0.05,2), round(105333.27*1.05,2), 'AED', current_setting('jeet.admin_id')::uuid)
  ON CONFLICT (id) DO UPDATE SET status=EXCLUDED.status, subtotal_ex_vat=EXCLUDED.subtotal_ex_vat, grand_total_with_vat=EXCLUDED.grand_total_with_vat;
INSERT INTO public.quotation_lines (id, quotation_id, line_number, description, system, category, unit, quantity, unit_sell_price, unit_sell_price_after_discount, line_total, sort_order) VALUES (
  '91f77a13-7069-5e76-bebc-8bfe05abdea8'::uuid, 'aa984fc3-f5c6-5d3d-b972-14999502762f'::uuid, 1, 'Plaza Mosque & Grandiose Parking CCTV', 'GATE_BARRIER', 'GATE_BARRIER', 'LS', 1, 105333.27, 105333.27, 105333.27, 1) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tenders (id, created_by, title, project_name, client_name, location, deadline_date, budget, status, scope_of_work) VALUES (
  '34c102d3-9eac-5c56-b366-2cfd90bb2e2d'::uuid, current_setting('jeet.admin_id')::uuid, 'SUPPLY & INSTALLATION OF GATE BARRIER – Gate 3', 'SUPPLY & INSTALLATION OF GATE BARRIER – Gate 3', 'TSC Limited (Sustainable City)', 'UAE', COALESCE('2026-03-27', CURRENT_DATE + 14), 11400.0, 'Submitted', 'SUPPLY & INSTALLATION OF GATE BARRIER – Gate 3')
  ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, budget=EXCLUDED.budget, status=EXCLUDED.status;
INSERT INTO public.boqs (id, tender_id, created_by, status, version, items, cost_elements, financials) VALUES (
  '4b06c1da-a589-51dd-a91b-d1f0a9d7ada7'::uuid, '34c102d3-9eac-5c56-b366-2cfd90bb2e2d'::uuid, current_setting('jeet.admin_id')::uuid, 'draft', 1, '[]'::jsonb, '{}'::jsonb, jsonb_build_object('total_selling_price', 11400.0, 'unit_selling_price', 11400.0))
  ON CONFLICT (id) DO UPDATE SET financials=EXCLUDED.financials;
INSERT INTO public.quotations (id, quotation_number, revision, status, boq_id, project_id, project_ref, client_id, client_name, quotation_date, valid_until, subject, subtotal_ex_vat, subtotal_after_discount, vat_amount, grand_total_with_vat, currency, prepared_by) VALUES (
  'a49d1ae2-60c9-5633-b501-09c09ea86a70'::uuid, '001-JEET- INTECH-DSC-018-2026', 0, 'SENT_TO_CLIENT', '4b06c1da-a589-51dd-a91b-d1f0a9d7ada7'::uuid, '34c102d3-9eac-5c56-b366-2cfd90bb2e2d'::uuid, 'DSC-018-2026', '82037870-19bb-59a7-aa74-24bd9ea37f1e'::uuid, 'TSC Limited (Sustainable City)', COALESCE('2026-03-18', CURRENT_DATE), COALESCE('2026-03-27', CURRENT_DATE + 14), 'SUPPLY & INSTALLATION OF GATE BARRIER – Gate 3', 11400.0, 11400.0, round(11400.0*0.05,2), round(11400.0*1.05,2), 'AED', current_setting('jeet.admin_id')::uuid)
  ON CONFLICT (id) DO UPDATE SET status=EXCLUDED.status, subtotal_ex_vat=EXCLUDED.subtotal_ex_vat, grand_total_with_vat=EXCLUDED.grand_total_with_vat;
INSERT INTO public.quotation_lines (id, quotation_id, line_number, description, system, category, unit, quantity, unit_sell_price, unit_sell_price_after_discount, line_total, sort_order) VALUES (
  'd03ec922-e6ba-51b4-8963-e7f85c88b45e'::uuid, 'a49d1ae2-60c9-5633-b501-09c09ea86a70'::uuid, 1, 'SUPPLY & INSTALLATION OF GATE BARRIER – Gate 3', 'GATE_BARRIER', 'GATE_BARRIER', 'LS', 1, 11400.0, 11400.0, 11400.0, 1) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tenders (id, created_by, title, project_name, client_name, location, deadline_date, budget, status, scope_of_work) VALUES (
  '7dc98944-c8be-5148-9525-8ccb9d220297'::uuid, current_setting('jeet.admin_id')::uuid, 'Maintenance ACCESS CONTROL SYSTEM of Residential blocks and public areas', 'Maintenance ACCESS CONTROL SYSTEM of Residential blocks and public areas', 'TSC Limited (Sustainable City)', 'UAE', COALESCE('2026-04-01', CURRENT_DATE + 14), 16928.25, 'Submitted', 'Maintenance ACCESS CONTROL SYSTEM of Residential blocks and public areas')
  ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, budget=EXCLUDED.budget, status=EXCLUDED.status;
INSERT INTO public.boqs (id, tender_id, created_by, status, version, items, cost_elements, financials) VALUES (
  'ccfc74c6-c1c8-59f9-b6b0-7741470f439c'::uuid, '7dc98944-c8be-5148-9525-8ccb9d220297'::uuid, current_setting('jeet.admin_id')::uuid, 'draft', 1, '[]'::jsonb, '{}'::jsonb, jsonb_build_object('total_selling_price', 16928.25, 'unit_selling_price', 16928.25))
  ON CONFLICT (id) DO UPDATE SET financials=EXCLUDED.financials;
INSERT INTO public.quotations (id, quotation_number, revision, status, boq_id, project_id, project_ref, client_id, client_name, quotation_date, valid_until, subject, subtotal_ex_vat, subtotal_after_discount, vat_amount, grand_total_with_vat, currency, prepared_by) VALUES (
  'a069dcba-12dc-5a4b-bac3-a0933754e8ce'::uuid, '001-JEET- INTECH-DSC-020-2026', 1, 'SENT_TO_CLIENT', 'ccfc74c6-c1c8-59f9-b6b0-7741470f439c'::uuid, '7dc98944-c8be-5148-9525-8ccb9d220297'::uuid, 'DSC-020-2026', '82037870-19bb-59a7-aa74-24bd9ea37f1e'::uuid, 'TSC Limited (Sustainable City)', COALESCE('2026-03-23', CURRENT_DATE), COALESCE('2026-04-01', CURRENT_DATE + 14), 'Maintenance ACCESS CONTROL SYSTEM of Residential blocks and public areas', 16928.25, 16928.25, round(16928.25*0.05,2), round(16928.25*1.05,2), 'AED', current_setting('jeet.admin_id')::uuid)
  ON CONFLICT (id) DO UPDATE SET status=EXCLUDED.status, subtotal_ex_vat=EXCLUDED.subtotal_ex_vat, grand_total_with_vat=EXCLUDED.grand_total_with_vat;
INSERT INTO public.quotation_lines (id, quotation_id, line_number, description, system, category, unit, quantity, unit_sell_price, unit_sell_price_after_discount, line_total, sort_order) VALUES (
  '55de52be-8445-5e16-9d0c-033f40d15d4a'::uuid, 'a069dcba-12dc-5a4b-bac3-a0933754e8ce'::uuid, 1, 'Maintenance ACCESS CONTROL SYSTEM of Residential blocks and public areas', 'ACS', 'ACS', 'LS', 1, 16928.25, 16928.25, 16928.25, 1) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tenders (id, created_by, title, project_name, client_name, location, deadline_date, budget, status, scope_of_work) VALUES (
  '88d5efc9-ef46-5489-a395-7608357f5126'::uuid, current_setting('jeet.admin_id')::uuid, 'Maintenance Gate barrier_Arm Replace garden Villas', 'Maintenance Gate barrier_Arm Replace garden Villas', 'TSC Limited (Sustainable City)', 'UAE', COALESCE('2026-04-03', CURRENT_DATE + 14), 13821.65, 'Submitted', 'Maintenance Gate barrier_Arm Replace garden Villas')
  ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, budget=EXCLUDED.budget, status=EXCLUDED.status;
INSERT INTO public.boqs (id, tender_id, created_by, status, version, items, cost_elements, financials) VALUES (
  '4379d236-429f-5157-b021-c56eb5fb1361'::uuid, '88d5efc9-ef46-5489-a395-7608357f5126'::uuid, current_setting('jeet.admin_id')::uuid, 'draft', 1, '[]'::jsonb, '{}'::jsonb, jsonb_build_object('total_selling_price', 13821.65, 'unit_selling_price', 13821.65))
  ON CONFLICT (id) DO UPDATE SET financials=EXCLUDED.financials;
INSERT INTO public.quotations (id, quotation_number, revision, status, boq_id, project_id, project_ref, client_id, client_name, quotation_date, valid_until, subject, subtotal_ex_vat, subtotal_after_discount, vat_amount, grand_total_with_vat, currency, prepared_by) VALUES (
  '59ac3c7d-6546-53d9-8e08-41188e2dd39d'::uuid, '001-JEET- INTECH-DSC-021-2026', 1, 'SENT_TO_CLIENT', '4379d236-429f-5157-b021-c56eb5fb1361'::uuid, '88d5efc9-ef46-5489-a395-7608357f5126'::uuid, 'DSC-021-2026', '82037870-19bb-59a7-aa74-24bd9ea37f1e'::uuid, 'TSC Limited (Sustainable City)', COALESCE('2026-03-25', CURRENT_DATE), COALESCE('2026-04-03', CURRENT_DATE + 14), 'Maintenance Gate barrier_Arm Replace garden Villas', 13821.65, 13821.65, round(13821.65*0.05,2), round(13821.65*1.05,2), 'AED', current_setting('jeet.admin_id')::uuid)
  ON CONFLICT (id) DO UPDATE SET status=EXCLUDED.status, subtotal_ex_vat=EXCLUDED.subtotal_ex_vat, grand_total_with_vat=EXCLUDED.grand_total_with_vat;
INSERT INTO public.quotation_lines (id, quotation_id, line_number, description, system, category, unit, quantity, unit_sell_price, unit_sell_price_after_discount, line_total, sort_order) VALUES (
  '37470747-c274-533e-944f-5efd7b558e12'::uuid, '59ac3c7d-6546-53d9-8e08-41188e2dd39d'::uuid, 1, 'Maintenance Gate barrier_Arm Replace garden Villas', 'GATE_BARRIER', 'GATE_BARRIER', 'LS', 1, 13821.65, 13821.65, 13821.65, 1) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tenders (id, created_by, title, project_name, client_name, location, deadline_date, budget, status, scope_of_work) VALUES (
  'cebd9d26-f8bc-5856-97e7-48a92df25cee'::uuid, current_setting('jeet.admin_id')::uuid, 'Maintenance Gate barrier_Arm Replace Clusters', 'Maintenance Gate barrier_Arm Replace Clusters', 'TSC Limited (Sustainable City)', 'UAE', COALESCE('2026-04-03', CURRENT_DATE + 14), 14215.0, 'Submitted', 'Maintenance Gate barrier_Arm Replace Clusters')
  ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, budget=EXCLUDED.budget, status=EXCLUDED.status;
INSERT INTO public.boqs (id, tender_id, created_by, status, version, items, cost_elements, financials) VALUES (
  'e6d47d7f-4f3b-5e64-8456-384e6540cdf1'::uuid, 'cebd9d26-f8bc-5856-97e7-48a92df25cee'::uuid, current_setting('jeet.admin_id')::uuid, 'draft', 1, '[]'::jsonb, '{}'::jsonb, jsonb_build_object('total_selling_price', 14215.0, 'unit_selling_price', 14215.0))
  ON CONFLICT (id) DO UPDATE SET financials=EXCLUDED.financials;
INSERT INTO public.quotations (id, quotation_number, revision, status, boq_id, project_id, project_ref, client_id, client_name, quotation_date, valid_until, subject, subtotal_ex_vat, subtotal_after_discount, vat_amount, grand_total_with_vat, currency, prepared_by) VALUES (
  'e11f02ce-b0bc-59b4-b7e1-e8a96f4b27b3'::uuid, '001-JEET- INTECH-DSC-022-2026', 0, 'SENT_TO_CLIENT', 'e6d47d7f-4f3b-5e64-8456-384e6540cdf1'::uuid, 'cebd9d26-f8bc-5856-97e7-48a92df25cee'::uuid, 'DSC-022-2026', '82037870-19bb-59a7-aa74-24bd9ea37f1e'::uuid, 'TSC Limited (Sustainable City)', COALESCE('2026-03-25', CURRENT_DATE), COALESCE('2026-04-03', CURRENT_DATE + 14), 'Maintenance Gate barrier_Arm Replace Clusters', 14215.0, 14215.0, round(14215.0*0.05,2), round(14215.0*1.05,2), 'AED', current_setting('jeet.admin_id')::uuid)
  ON CONFLICT (id) DO UPDATE SET status=EXCLUDED.status, subtotal_ex_vat=EXCLUDED.subtotal_ex_vat, grand_total_with_vat=EXCLUDED.grand_total_with_vat;
INSERT INTO public.quotation_lines (id, quotation_id, line_number, description, system, category, unit, quantity, unit_sell_price, unit_sell_price_after_discount, line_total, sort_order) VALUES (
  '5d893527-6836-5496-9ece-fca27aaaa9a5'::uuid, 'e11f02ce-b0bc-59b4-b7e1-e8a96f4b27b3'::uuid, 1, 'Maintenance Gate barrier_Arm Replace Clusters', 'GATE_BARRIER', 'GATE_BARRIER', 'LS', 1, 14215.0, 14215.0, 14215.0, 1) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.tenders (id, created_by, title, project_name, client_name, location, deadline_date, budget, status, scope_of_work) VALUES (
  'a6797c93-9d4e-5783-a6f4-8fd06ba9a893'::uuid, current_setting('jeet.admin_id')::uuid, 'CCTV ZEN AREA', 'CCTV ZEN AREA', 'TSC Limited (Sustainable City)', 'UAE', COALESCE('2026-04-03', CURRENT_DATE + 14), 2716.0, 'Submitted', 'CCTV ZEN AREA')
  ON CONFLICT (id) DO UPDATE SET title=EXCLUDED.title, budget=EXCLUDED.budget, status=EXCLUDED.status;
INSERT INTO public.boqs (id, tender_id, created_by, status, version, items, cost_elements, financials) VALUES (
  'a7fe84a1-d793-5038-af30-fba34eca734f'::uuid, 'a6797c93-9d4e-5783-a6f4-8fd06ba9a893'::uuid, current_setting('jeet.admin_id')::uuid, 'draft', 1, '[]'::jsonb, '{}'::jsonb, jsonb_build_object('total_selling_price', 2716.0, 'unit_selling_price', 2716.0))
  ON CONFLICT (id) DO UPDATE SET financials=EXCLUDED.financials;
INSERT INTO public.quotations (id, quotation_number, revision, status, boq_id, project_id, project_ref, client_id, client_name, quotation_date, valid_until, subject, subtotal_ex_vat, subtotal_after_discount, vat_amount, grand_total_with_vat, currency, prepared_by) VALUES (
  '086ea608-5a8a-5717-a0fc-0e881768f09a'::uuid, '001-JEET- INTECH-DSC-023-2026', 0, 'SENT_TO_CLIENT', 'a7fe84a1-d793-5038-af30-fba34eca734f'::uuid, 'a6797c93-9d4e-5783-a6f4-8fd06ba9a893'::uuid, 'DSC-023-2026', '82037870-19bb-59a7-aa74-24bd9ea37f1e'::uuid, 'TSC Limited (Sustainable City)', COALESCE('2026-03-25', CURRENT_DATE), COALESCE('2026-04-03', CURRENT_DATE + 14), 'CCTV ZEN AREA', 2716.0, 2716.0, round(2716.0*0.05,2), round(2716.0*1.05,2), 'AED', current_setting('jeet.admin_id')::uuid)
  ON CONFLICT (id) DO UPDATE SET status=EXCLUDED.status, subtotal_ex_vat=EXCLUDED.subtotal_ex_vat, grand_total_with_vat=EXCLUDED.grand_total_with_vat;
INSERT INTO public.quotation_lines (id, quotation_id, line_number, description, system, category, unit, quantity, unit_sell_price, unit_sell_price_after_discount, line_total, sort_order) VALUES (
  'a4edc5ee-fd5e-5305-8e5c-bfdc81d68909'::uuid, '086ea608-5a8a-5717-a0fc-0e881768f09a'::uuid, 1, 'CCTV ZEN AREA', 'CCTV', 'CCTV', 'LS', 1, 2716.0, 2716.0, 2716.0, 1) ON CONFLICT (id) DO NOTHING;

NOTIFY pgrst, 'reload schema';
COMMIT;
-- summary: 6 leads -> tenders + boqs + quotations